### ISSUE TITLE
Cannot recognize excel file 

### ISSUE THREAD

**Issue by apchenjun** [AJMitev/FileTypeChecker#17]
Cannot recognize excel file xlsx/xls
I uploaded process.xlsx but FileTypeInterrogator
Think it is a jar file
![image](https://user-images.githubusercontent.com/4964551/144952926-89716f77-ef8a-4ff5-91fc-f3993aef95e0.png)

![image](https://user-images.githubusercontent.com/4964551/144952960-e41ef085-39c8-48bc-8617-8ba4a15896c5.png)

**Comment by AJMitev** [comment]
Are you sure that you are using this library, because we didn't have Interface or class or namespace called FileTypeInterrogator?

**Comment by cedvdb** [comment]
excel is parsed as docx for me
