### ISSUE TITLE
How to check if file type is supported?

### ISSUE THREAD

**Issue by RetainPhil** [AJMitev/FileTypeChecker#19]
It would be useful to be able to verify what file type validations are currently supported, just from the extension. In the context to verifying that a file is what it claims to be, by comparing extension with the resolved extension from FileTypeValidator.GetFileType(stream) however, I still need to know or hard-code what extensions FileTypeValidator actually supports in the first place.

For example:

    FileTypeValidator.IsSupportedType("png"); //true
    FileTypeValidator.IsSupportedType("webp"); //false

**Comment by RetainPhil** [comment]
Just for a bit more context, I end up writing something like this as a work-around:

        /// <summary>
        /// Just for exposing FileTypeValidator.FileTypes
        /// </summary>
        private abstract class TypeValidator : FileTypeValidator
        {
            public static new IReadOnlyCollection<IFileType> FileTypes
                => FileTypeValidator.FileTypes;
        }

        private bool IsSignatureBitsValid(IFormFile file, string extension)
        {
            if (!TypeValidator.FileTypes.Any(t => t.Extension == extension))
            {
                return true; //or false
            }

            using var stream = file.OpenReadStream();
            if (!FileTypeValidator.IsTypeRecognizable(stream))
            {
                return false;
            }

            var fileType = FileTypeValidator.GetFileType(stream);
            return fileType.Extension == extension;
        }

**Comment by RetainPhil** [comment]
I guess I was saying that there's a semantic difference between a file type which has a validator, but type is not recognized because the signature bits are invalid and a file which doesn't even have any validator to begin with. IsTypeRegnoizable(stream) doesn't delineate between the 2 cases.

**Comment by yasserss** [comment]
quick question guys , does filesteam.IsImage  , incluse Webp images ?

**Comment by AJMitev** [comment]
At the moment no, but I am planning to include it in the next release. If you want your code to recognize it you can implement [ a custom type](https://github.com/AJMitev/FileTypeChecker/wiki/Create-custom-type)

**Comment by yasserss** [comment]
@AJMitev  sorry to bother you again , can you say if this code is safe enought to test for webp ? 

```
 public class WebPFileType : FileType
    {
        private static readonly string name = "WebPacl Custom Type 1.0";
        private static readonly string extension = "webp";
        private static readonly byte[] magicBytes = new byte[] { 0x52, 0x49 };

        public WebPFileType() : base(name, extension, magicBytes) { }
    }
```

**Comment by AJMitev** [comment]
It's looking good :)

**Comment by yasserss** [comment]
> @AJMitev sorry to bother you again , can you say if this code is safe enought to test for webp ?
> 
> ```
>  public class WebPFileType : FileType
>     {
>         private static readonly string name = "WebPacl Custom Type 1.0";
>         private static readonly string extension = "webp";
>         private static readonly byte[] magicBytes = new byte[] { 0x52, 0x49 };
> 
>         public WebPFileType() : base(name, extension, magicBytes) { }
>     }
> ```

@AJMitev  can you help me out please ? i created my custom type , is when a test a wepb img ( i double checked the header for magic bytes ) but the code 'fileStream.Is<WebPFileType>()' always return false  , any ideas why?

**Comment by AJMitev** [comment]
Try this:
`using (var fileStream = File.OpenRead("myFileLocation"))
{
    var isRecognizableType = FileTypeValidator.IsTypeRecognizable(fileStream);

    ...
}`

If isRecognizableType is false then you are not registered your type correctly. And you should [read this](https://github.com/AJMitev/FileTypeChecker/wiki/What-types-of-file-are-supported%3F#register-custom-types).

**Comment by yasserss** [comment]
@AJMitev i did registered in the startup class 
and isRecognizableType return true

**Comment by AJMitev** [comment]
Well, this is easy to debug mate, just retrieve the type and see what you will receive.

```
 var fileType = FileTypeValidator.GetFileType(fileStream);
```

Now when I saw the bytes you are defined in your type, I bet it will return AVI instead of WebP, this is because the beginning of both types are the same and for now FindMaxScore returns the first type that scores the highest. In that case AVI. 

For now I can recommend you to set more specific byte definition. In near future I will improve the behavior.

**Comment by RetainPhil** [comment]
svg is just xml internally I think? It's not binary format I don't think it has a specific signature.
