### ISSUE TITLE
.xlsx is recognized as .docx

### ISSUE THREAD

**Issue by antonis0490-cy** [AJMitev/FileTypeChecker#20]
**Is your feature request related to a problem? Please describe.**
When we upload a file with extension .xlsx, the library recognizes it with an exception of .docx (by calling 
fileTypeObject.Extension)

**Describe the solution you'd like**
It would be nice if document types extensions are distinguished 

**Describe alternatives you've considered**
Possibly instead of isDocument, that can break down to isDocx, isXlsx etc

**Additional context**

**Comment by AJMitev** [comment]
This is not an issue. If you check [this list](https://en.wikipedia.org/wiki/List_of_file_signatures) with file signatures you will see that they have the same one.
