### ISSUE TITLE
Support for HEIC file type

### ISSUE THREAD

**Issue by kamalsivalingam** [AJMitev/FileTypeChecker#21]
**Describe the bug**
GetFileType method is blowing up when testing HEIC file.

This is more of a question. 
Is HEIC file type supported?
If its not supported, are there plans to support it, as this is the default file format for ios

**Comment by AJMitev** [comment]
As it is [described into the documentation page](https://github.com/AJMitev/FileTypeChecker/wiki/What-types-of-file-are-supported%3F) HEIC file type is not currently supported. If you need this format to be recognized you can do it by implementing a [custom type](https://github.com/AJMitev/FileTypeChecker/wiki/Create-custom-type). I will definitely consider to include it in the future but I am not sure when there will be a new version as I have plenty of stuff going on.

**Comment by AJMitev** [comment]
Support to this file type will be added within next release
