### ISSUE TITLE
Nuget package built with Debug mode

### ISSUE THREAD

**Issue by guilhermeolisi** [AJMitev/FileTypeChecker#23]
**Describe the bug**
Hi, I'm using your FileTypeChecker package from nuget in my project and when I run Windows App Certification Kit to publish to Windows store, I get a error message saying that your package's dll files were build in Debug mode. Would you publish a nuget package built with Release mode?

**To Reproduce**
1. try publish a app with FileTypeChecker to a windows store

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 
 - Version

**Comment by AJMitev** [comment]
A new version is released. This time I am 100% that it is in Release mode.
