### ISSUE TITLE
File Version of latest repository is version 1.0.0.0. 

### ISSUE THREAD

**Issue by YellowCobus** [AJMitev/FileTypeChecker#26]
I use to make use of the Nuget package version 3.0.0 that was available and earlier this week upgraded to the latest version 4.0.0.
The file version on the latest Nuget package (4.0.0) reflects as 1.0.0.0. This causes problems with some installers (like wix). Problem comes in when one tries to install your new deployment package that was made with these tools. It will not replace the file of the previous Nuget package version on the server as that file had a file version of 3.0.0.0. So as the new package file version is seen as older it just gets skipped.

This could be potential problem for other users in the future as well.

Product version of file also shows 1.0.0 instead of 4.0.0 where previous package file was 3.0.0

**Comment by AJMitev** [comment]
I am not sure if this is a problem related with the new version. You can check the nuspec file yourself, the version is 4.0.0. I tested it with nuget and it works as expected. I am not familiar with wix and how it works so if you have any suggestions make a pull request.
