### ISSUE TITLE
stream of dll reported as exe

### ISSUE THREAD

**Issue by ilmenwe** [AJMitev/FileTypeChecker#29]
**Describe the bug**
A filestream of a dll is identified as DOS MZ executable .exe

**To Reproduce**
Use a local windows dll like one provided by dot.net 7 like System.Windows.Extensions.dll
Run it trough var fileType = FileTypeValidator.GetFileType(stream);
Examine the fileType.

**Expected behavior**
reported as a dll / dynamic linked library.

**Screenshots**
![image](https://github.com/AJMitev/FileTypeChecker/assets/6985194/8a68a83c-4866-4626-ba06-fc4c784305c0)

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise
 - .net 7.0
 - FileTypeChecker 4.0.0 installed trough nuget.

**Additional context**
It's not really important, I mean I will not allow executables either, but it would be nice to know if it's a exe or dll if possible.

**Comment by AJMitev** [comment]
This is not an issue. If you check (that article)[https://en.wikipedia.org/wiki/List_of_file_signatures] you will see that the exec files and  the dynamic linked libraries have the same signatures.

**Comment by ilmenwe** [comment]
Fair point did take a look around now. 
It's not part of the MZ magic bytes, but would be stored in a PE optional header. 
So I will just add a local solution that gives me extra details I need.
