### ISSUE TITLE
Can you add the Byte parameter?

### ISSUE THREAD

**Issue by hedandan1989** [AJMitev/FileTypeChecker#30]
In different situations, the file data source may be either stream or bytes, and although it can be converted to each other, the conversion of large files will result in double the memory usage.

**Comment by duynl71** [comment]
According to https://en.wikipedia.org/wiki/List_of_file_signatures, the docx/xlsx/zip share the same signature. So I guess @hedandan1989 suggest better behavior for these file types.

**Comment by hedandan1989** [comment]
> And what that behavior would be?

Sorry for waiting so long to reply.
I have edited the theme again.

**Comment by AJMitev** [comment]
Implemented with commit 8632b74aff6c50ce11b1429de43e5523db916beb
