### ISSUE TITLE
More intelligent recognition of file types

### ISSUE THREAD

**Issue by hedandan1989** [AJMitev/FileTypeChecker#31]
According to https://en.wikipedia.org/wiki/List_of_file_signatures, the docx/xlsx/zip share the same signature. So I guess @hedandan1989 suggest better behavior for these file types.

_Originally posted by @duynl71 in https://github.com/AJMitev/FileTypeChecker/issues/30#issuecomment-1759727959_
            
Many file types will use the same recognition method. Is it possible to recognize them more intelligently, as I have now tried to recognize office files as zip.
But some online websites can be correctly identified.

Thanks。

**Comment by AJMitev** [comment]
I am not sure what you are mean by "more intelligent" recognition. A [.docx](https://en.wikipedia.org/wiki/Office_Open_XML) file is just a [.zip](https://en.wikipedia.org/wiki/Zip_(file_format)) file. This is how it is. If you have some suggestion please implement it and make a pull request. I will be more than happy to review and merge it.
