### ISSUE TITLE
FileType magic sequence with offset cannot be recognised

### ISSUE THREAD

**Issue by andrea-quartini** [AJMitev/FileTypeChecker#34]
If a file type magic sequence have an offset, it cannot be recognised because the offset is applied to the magic byte sequence as well; see for instance Mp4 and M4v file types

1. Into the FileTypeValidatorTests.cs, add a test case for Mp4 file type and file name "test.mp4"
2. Run the test
3. Test throws an exception on GetFileType method

**Comment by AJMitev** [comment]
This will be fixed in next release.

**Comment by AJMitev** [comment]
@Chida82 I added this file to the test cases and it worked, can you please specify your problem and maybe provide me with some code example that I can use?

**Comment by fedebona** [comment]
it works with 4.1.1 after fix of bug #34
