### ISSUE TITLE
byte[] or stream versions of apis

### ISSUE THREAD

**Issue by darrinmulligan** [AJMitev/FileTypeChecker#35]
We are attempting to use the library in out application, but there is one issues. 

Here is the background.   In our application we have the file contents provided in a byte array which can be easily converted to a stream. 

The filetypechecker library however requires the file to be provided as a filestream.  We therefore need to write the byte[] to a filestream 
 and create a physical file so it can be consumed by the library apis.   This becomes an efficiency issue when dealing with large volumes of files. 

Request:  could we get a verion of the apis which supports a byte[] or a stream instead of a filestream.  

Thanks

**Comment by AJMitev** [comment]
I believe you are mistaken. Both methods - FileTypeValidator.IsTypeRecognizable and FileTypeValidator.GetFileType have overloads with signature accepting [Stream](https://github.com/AJMitev/FileTypeChecker/blob/master/FileTypeChecker/FileTypeValidator.cs#L93) and [byte[]](https://github.com/AJMitev/FileTypeChecker/blob/master/FileTypeChecker/FileTypeValidator.cs#L118)

**Comment by darrinmulligan** [comment]
Amazing!  Thanks.  I'll give it a try.

⁣Regards 
Darrin​
