### ISSUE TITLE
Error on validating HTML files

### ISSUE THREAD

**Issue by senal** [AJMitev/FileTypeChecker#36]
**Describe the bug**
I get the following error when trying to validate an HTML file type. 

`FileTypeChecker.Exceptions.TypeNotFoundException: No registered type matches the provided sequence!`

The file throwing the error was generated through a system. ( I removed the content to make it less sensitive)
But when I create an html file manually. It passes the validation.

I noted this behaviour is upto version `3.0.0` with `.NET 6`. 
However, I can't use version `3.0.0` with `.NET 8`.  Can you also confirm whether I can use version `3` with .net 8?

These 2 files are passing without any issues but the issue starts from version 4.0.0.

FileTypeChecker version : `4.1.1`
Framework : `.NET 8`

**To Reproduce**
I have attached a sample project with the 2 html files.
[filecheck.zip](https://github.com/user-attachments/files/16264195/filecheck.zip)

Just build the project and run the console application.

```
    using FileTypeChecker;
  
   var filePath1 = Path.Combine(Directory.GetCurrentDirectory(), "file1.html");
   var filePath2 = Path.Combine(Directory.GetCurrentDirectory(), "file2.html");
   using var fileStream = File.OpenRead(filePath1);
   var fileType = FileTypeValidator.GetFileType(fileStream);
   Console.WriteLine(fileType.Extension);
```
The `file1.html` is causing the problem. You can toggle the `filePath1` and `filePath2` for testing. The `file2.html` is printing the extension while `file1.html` throwing an exception.
 

**Expected behavior**
I'm expecting the HTML file to be validated from the version 4.0 upwards.
 

**Screenshots**
Exception
![image](https://github.com/user-attachments/assets/5091ba30-466b-4759-8e56-755fd8edad6b)

Success:
![image](https://github.com/user-attachments/assets/a75420fa-fbe4-4b55-b5c7-0d12d6c15ad3)

**Desktop (please complete the following information):**
 - OS: [windows]

**Additional context**
Feel free to request any information.

**Comment by AJMitev** [comment]
This is not really a problem in the library but rather in the file. To avoid the exception you can use FileTypeValidator.IsTypeRecognizable(fileStream).

I am sorry but I don't have free time to spare debugging the wrong file. If you want exclusive support you can [become a member ](https://buymeacoffee.com/ajmitev/membership) and join the discord server.

**Comment by senal** [comment]
@AJMitev , Thanks for your feedback. You sure this nothing to do with the .net 8 ? Have you tried running your tests with .net 8?
This file perfectly works with .net 6 and version 3.0.0.
I can't load the version 3.0.0 with .net 8.

**Comment by AJMitev** [comment]
Yes this has nothing to do with the version of .NET. This exception is thrown when the bytes does not match with any registered type.

**Comment by senal** [comment]
Thanks @AJMitev !
I have downgraded the version to 3.0.0 with .net 8.
And it worked!
I will spare time to do a full debug and let you know if I find anything.
