### ISSUE TITLE
Blob mp3 signature not supported

### ISSUE THREAD

**Issue by jim-craane** [AJMitev/FileTypeChecker#9]
Most of the mp3 file types are MPEG-1 Audio Layer 3 (MP3) audio files with hex signatures '49 44 33' and 'FF FB. But in our scenario we record blob data as mp3 in the client. With this the signature is 'FF E3' in a MPEG audio file frame synch pattern.

The following signatures should be added to the mp3 filetype: 'FF Ex' and 'FF Fx' where x is a wildcard. https://www.garykessler.net/library/file_sigs.html

Download blob mp3 recording with this signature:
https://gofile.io/d/REND6F

For now I added a custom file type as workaround.

**Comment by AJMitev** [comment]
This filetype is added in version 1.4.0. You can download it from here -https://www.nuget.org/packages/File.TypeChecker/1.4.0
